# 文件: .github/workflows/build.yml
name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android Licenses
        shell: bash
        run: |
          yes | sdkmanager --licenses > /dev/null 2>&1 || true
          sdkmanager --update || true

      - name: Install Android SDK packages
        shell: bash
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0" --sdk_root=$ANDROID_SDK_ROOT

      - name: Setup Gradle 8.2.1
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.2.1"

      - name: Verify Gradle
        run: gradle -v

      - name: Build Debug APK
        run: gradle :app:assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk